// <auto-generated />
namespace TWG.EASDataService.DbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class temp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(temp));
        
        string IMigrationMetadata.Id
        {
            get { return "201405151620518_temp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
