// <auto-generated />
namespace twg.chk.DataService.DbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddStaticContentLink : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStaticContentLink));
        
        string IMigrationMetadata.Id
        {
            get { return "201404101441200_AddStaticContentLink"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
